POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "username": "wangdongliyanxiang@hotmail.com",
    "password": "123"
}
###
POST http://localhost:3000/api/admin/librian HTTP/1.1
content-type: application/json

{
    "firstname": "Dong",
    "lastname": "Wang",
    "email": "wangdongliyanxiang@hotmail.com",
    "password": "123",
    "phoneNumber":"123343",
    "roles":["admin"]
}
###
GET http://localhost:3000/api/admin/librian HTTP/1.1

###
PUT http://localhost:3000/api/admin/librian/5cba8791ae03681c077df6b0 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Indhbmdkb25nbGl5YW54aWFuZ0Bob3RtYWlsLmNvbSIsInJvbGVzIjpbImFkbWluIiwibGliIl0sImlhdCI6MTU1NTk2NzQ3MywiZXhwIjoxNTU2MDEwNjczfQ.LPKQv-eaLFiSUNFegNI3vdwGaU2tGjvqej1vTsbT2s0


{
    "firstname": "Dong12",
    "lastname": "Wang3",
    "email": "wangdongliyanxiang@hotmail.com",
    "password": "123",
    "phoneNumber":"7788888",
    "roles":["admin", "lib"]
}

###

GET http://localhost:3000/validate/checkEmailDuplicate/wangdongliyanxiang@hotmail.com HTTP/1.1

###
POST http://localhost:3000/api/admin/librian HTTP/1.1
content-type: application/json

{
    "firstname": "handsome",
    "lastname": "boy",
    "email": "hboy@m.com",
    "password": "123",
    "phoneNumber":"123343",
    "roles":["admin", "lib"]
}
###
POST http://localhost:3000/api/admin/librian/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Indhbmdkb25nbGl5YW54aWFuZ0Bob3RtYWlsLmNvbSIsInJvbGVzIjpbImFkbWluIiwibGliIl0sImlhdCI6MTU1NTk2NzQ3MywiZXhwIjoxNTU2MDEwNjczfQ.LPKQv-eaLFiSUNFegNI3vdwGaU2tGjvqej1vTsbT2s0

{
    "firstname": "pretty",
    "lastname": "girl",
    "email": "pgirl@m.com",
    "password": "123",
    "phoneNumber":"123343",
    "roles":["admin", "lib"]
}

###
GET http://localhost:3000/api/admin/librian/5cba8791ae03681c077df6b0 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Indhbmdkb25nbGl5YW54aWFuZ0Bob3RtYWlsLmNvbSIsInJvbGVzIjpbImFkbWluIiwibGliIl0sImlhdCI6MTU1NTk2NzQ3MywiZXhwIjoxNTU2MDEwNjczfQ.LPKQv-eaLFiSUNFegNI3vdwGaU2tGjvqej1vTsbT2s0

