###
POST  http://localhost:3000/reader/add HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "firstname":"Bilegee",
    "lastname":"Jargalsaikhan",
    "email":"bilgee12.py@gmail.com",
    "password":"123"
}
###
DELETE   http://localhost:3000/reader/delete/5cba84fac619ee0414390371 HTTP/1.1
Content-Type: application/json; charset=utf-8

###
PUT http://localhost:3000/reader/update/5cbded3b51d3740923253004 HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "firstname":"Zula1",
    "lastname":"Jargalsaikhan",
    "email":"bilgeefsffa.py@gmail.com",
    "password":"123"
}

###
GET http://localhost:3000/reader/ HTTP/1.1